### PR TITLE
Create bubble sort on js and php

### PR DESCRIPTION
**Pull request by Matrix278**
Hello, I created bubble sorting algorithm on JavaScript and PHP

### CODE REVIEW

**Comment by Matrix278** [comment]
If you gonna merge that, please add label of `hacktoberfest-accepted`

**Comment by LON3WO7F** [comment]
@Matrix278  Please Include Comments in your code.

**Comment by Matrix278** [comment]
Hmm, can't change this now, I think I will recreate the PR, seems branch lost

**Comment by LON3WO7F** [comment]
> Hmm, can't change this now, I think I will recreate the PR, seems branch lost

Hey @Matrix278  you can directly changed it by clicking on above commits and then edit it.

**Comment by Matrix278** [comment]
> > Hmm, can't change this now, I think I will recreate the PR, seems branch lost
> 
> Hey @Matrix278 you can directly changed it by clicking on above commits and then edit it.

Still can't see how, I will just use new, that will be faster, also someone already added js

**Pull request closed without merging**
